# -*- coding: utf-8 -*-
"""Raf-DB BASEDCNN.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NI6ZMW7wkPorbBAmbt-YqMwoEWHhukY7
"""

from google.colab import drive
drive.mount('/content/drive')

cd /content/drive/My Drive/SOP_EmotionDetection/Code

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

X = np.load('BASE.npy')
X.shape

y = np.load('y.npy')

# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# Fitting SVM to the Training set
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(X_train, y_train)

# Predicting the Test set results
y_pred = classifier.predict(X_test)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

np.save('y_pred_base.npy',y_pred)
np.save('cm_base.npy',cm)

from sklearn.metrics import f1_score
f1_score(y_test, y_pred, average='macro')
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)